[package]
org = "g_agzaiyenth"
name = "hands_on_task"
version = "0.1.0"
distribution = "2201.12.6"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"
